import '../styles/globals.css'
import Layout from '../src/components/layout/Index'
import Head from 'next/head';
import { ThemeProvider } from '@material-ui/core/styles';
import theme from '../src/components/utils/theme'

function MyApp({ Component, pageProps }) {
  return (

    <> 
      <Head>
        <title>React Intern</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    <ThemeProvider theme={theme} >
      <Layout >
        <Component {...pageProps} />
      </Layout>
    </ThemeProvider>

    </>

  )
}

export default MyApp
